package mensajes;

public enum TipoMensaje {

	CONEXION_CS,
	CONEXION_CC,
	CONFIRMACION_CONEXION,

	SOLICITUD_LISTA_USUARIOS,
	RESPUESTA_LISTA_USUARIOS,
	SOLICITUD_LISTA_CANCIONES,
	RESPUESTA_LISTA_CANCIONES,

	SOLICITUD_CANCION,
	EMITIR_CANCION,
	PREPARADO_CS,
	PREPARADO_SC,
	RESPUESTA_CANCION_CC,

	ACTUALIZAR_CANC_RECEPTOR,
	CONFIRMACION_ACTUALIZACION_CANC,

	
	COMPROBAR_CANCION_CS,
	RESPUESTA_COMPROBACION_SC,
	
	DESCONEXION
	

}
