package mensajes;

public enum TipoMensaje {

	CONEXION,
	CONFIRMACION_CONEXION,
	DESCONEXION_CLIENTE,
//	CONFIRMACION_DESCONEXION_CLIENTE,

	SOLICITUD_LISTA_USUARIOS,
	RESPUESTA_LISTA_USUARIOS,
	SOLICITUD_LISTA_CANCIONES,
	RESPUESTA_LISTA_CANCIONES,

	SOLICITUD_CANCION,
	EMITIR_CANCION,
	PREPARADO_CS,
	PREPARADO_SC,

	CONEXION_CC,
	CONFIRMACION_CONEXION_CC,
	SOLICITUD_CANCION_CC,
	ENVIAR_CANCION_CC,

	DESCONEXION_CC,
	DESCONEXION_CS,
	DESCONEXION_SC,

}
