package mensajes;

public enum TipoMensaje {

	CONEXION,
	CONFIRMACION_CONEXION,
	DESCONEXION_CLIENTE,
	CONFIRMACION_DESCONEXION_CLIENTE,

	SOLICITUD_LISTA_USUARIOS,
	RESPUESTA_LISTA_USUARIOS,
	SOLICITUD_LISTA_CANCIONES,
	RESPUESTA_LISTA_CANCIONES,



}
